export { default as LayoutA } from './LayoutA'
export { default as LayoutB } from './LayoutB'
export { default as MobileLayout } from './MobileLayout'
export { default as Layouts } from './Layouts'
export { default as Thesis } from './Thesis'
