import { useState } from 'react'

import { getRandomItem } from '../utils'

const bios = [
  'Glories in aesthetic in all her forms; art, architecture, nature, and the like are equally venerated. He’s made a life’s work of delighting and participating in the facets of their inspiration via various routes of fashion, construction, and design.',
  'UI/UX designer, with a huge passion for Nutella.',
  'Driven by truth, we create remarkable, productive brand opportunity for clients who know that building brands builds business.',
  'An introvert addicted to extroverting. Now throw design in that dichotomy.',
  'We are the idea makers, the developers, the collaborators and the facilitators. We are nimble and enlightened. Every day presents new tests and new boundaries to push — and we are pumped.',
  'In a nutshell, I create beautiful things that move people, and seek out other creatives that do the same so I can capture, enhance, and share their stories.',
  'When not doing design, they can be found playing with their dog momo, eating avocados, or doing yoga.',
  "Possesses an almost supernatural ability to understand and articulate ideas. They're a thinker with an overdeveloped attention to detail.",
  'I split my time between designing websites and publications for clients and making my own books. When not working, I’m probably thinking about food, music, or dogs.',
  'Their way of thinking is a bit unexpected, often leading to very original ideas.',
  'An outside the box, big picture, strategic, concept driven thinker. I see the forest and the trees.',
  'We have principles of authenticity and simplicity with a research based approach.',
  'When people ask what I “do” for a living, I can’t think of a better word than “maker.”',
  'An online marketer that builds products people love to use.',
  'A graphic designer interested in communication at the intersection of language and culture.',
  'I have a passion for work that supports positive change for our planet.',
  'There’s an art to designing for the web, but not for the sake of art.',
  'Gradually I moved from crayons to graphite to acrylics and then to Adobe CS5.',
  'I am a thinker, maker, letterer, logoer, doer, drawer, brander, cup-cake eater, screen printer and fun haver.',
  'I am a visual communicator, collector, connector, and creator.',
  'In order to create compelling and creative communication concepts, I focus on the idea before the medium. Concept is the foundation of everything else.',
  'I post work on dribbble, write at Medium, post photos, speak at conferences, paint waves on reclaimed wood, and enjoy advising startups. I sometimes make random things with friends.',
  'Brings many years of varied, skill-honing experiences building brands for many of the world’s largest companies, including 13 years of in-house creative direction at Nike.',
  'A design practitioner who is as comfortable defining brand strategy as they are executing it.',
  'I divide my time between eating ramen, making art, and initiating collaborations ranging from both critical discourse to product design.',
  'We create brands, apps and websites. You will see the difference.',
  'I believe that honesty, simplicity, good dialogue with clients, and above all, the hard work are the key to create strong, lasting and remarkable design.',
  'I’m not the guitarist, or the soccer player, or the stand-up comedian. I’m just a designer and creative director who plays guitar, likes soccer and tells jokes every now and then.',
  'People tell us we have an attitude. We take that as a compliment.',
  'I love design, not just for it’s own sake but for what it can do for people.',
  'I’m obsessed with design because of the democratic nature of the analytical approach it encourages.',
  'Design is the ability to improve individual lives through tiny changes on a massive scale.',
  'User experience (UX) is how a person feels when using a system. My goal is to enhance those feelings.',
  'For me, design is a way to determine how things function, not just how they look. Design involves assembling the right people, asking and responding to questions, and iterating forms continuously.',
  'Integrates storytelling throughout their body of work and has developed an iconic style. Their disciplined and prolific production is based upon creation for its own sake.',
  'I am a creative problem solver with experience across all mediums, and have a passion for elevating brands through great visual design. I love to work with brands who are seeing a refresh, or who just want to continue evolving and looking towards the future.',
  'Brand is what. Design is how. Strategy is why.',
  'Design without borders. Our mission is to create lasting, meaningful connections between brands and their audience.',
  'In my free time I love to play tennis, walk in the city, cook a fun meal, hike, camp, and ski. I value authenticity, trust, dignity, value, and seeing the goodness in others.',
  'High-contrast. Thick and decisive, bold and iconic, blunt and minimal. A sterling muse smashed to atoms. With respect to the rules, there are no rules.',
  'Approximately 70% La Croix. Invested all of 2019 in becoming a better human, parent, and creative.',
  'We create thoughtful experiences for humans and propel brands with soul and substance.',
  'It’s my goal to help you craft your brand’s story, in a way that helps you engage with your audience and educate in what you’re offering them.',
  'I lead teams to positive outcomes combining my skills in product strategy, service design, user experience and product design.',
  'I HAVE BEEN IN YOUR SHOES FOR OVER A DECADE. I AM AN ENTREPRENEUR.',
  'You just bring the seed and we plant it, grow it, and harvest sweet corn.',
  'We believe in the power of brand—to shift mindsets, create markets, inspire innovation, and unleash movements. Every day, we work alongside visionary leaders and innovators who share our beliefs.',
  'Focused on creating smart, provocative, and conceptual work for editorial illustrations, covers, brands and various print and online visual communications. Through constant exploration of typography, imagery and illustration, my work transcends style.',
  'I collaborate with people, teams, and businesses to develop design systems, strategies, and processes to do better and more interesting creative work.',
  'This isn’t just design that looks pretty, but design that makes your company more valuable.',
  'I’m a Graphic Designer and Illustrator but more importantly I’m a Virgo.',
]

const emailCallsToAction = [
  'Hire me:',
  'Contact me:',
  'Reach out:',
  "Let's grab a coffee:",
  "Let's talk shop:",
  'Worship me:',
  "Let's collaborate:",
  'Tell me two truths and a lie:',
  "Let's talk design:",
  "Let's talk product:",
  "Let's talk brand:",
  "Let's grab drinks:",
  "Let's grab tacos:",
  "Let's build something beautiful:",
  'Send praise:',
  'Clap for me:',
]

const emailHandles = [
  'Hello',
  'Contact',
  'Hi',
  'Coffee',
  'Drinks',
  'Work',
  'Collaborate',
  'Design',
  'Think',
  'Whatsup',
  'Wave',
]

const titles = [
  'Designer',
  'Maker',
  'Creative Problem Solver',
  'Brand Builder',
  'Art Director',
  'UX/UI Designer',
  'Visual Communicator',
  'Design Practitioner',
  'Creative',
  'Design Lover',
  'Sr. Designer',
  'Sr. Jr. Designer',
  'Sr. UX/UI Designer',
  'Design Director',
  'Product Designer',
  'Product Design Director',
  'Product Maker',
  'Product Builder',
]

const firstNames = [
  'Charlie',
  'Finn',
  'Skyler',
  'Royal',
  'Armani',
  'Landry',
  'Frankie',
  'Sidney',
  'Riley',
  'Denver',
  'Robin',
  'Salem',
  'Yael',
  'Murphy',
  'Hollis',
  'Perry',
  'Jules',
  'Austen',
  'Jack',
  'Clarke',
  'Timber',
  'Dakota',
  'Jordan',
  'Avery',
  'Parker',
  'Blake',
  'Taylor',
  'Alex',
  'Justice',
  'Spencer',
  'Mylo',
  'Holland',
  'Andy',
  'Addison',
  'Corey',
  'Frances',
  'Ellis',
  'Shawn',
  'Tyler',
  'Morgan',
  'Jesse',
  'Jamie',
  'Drew',
  'Ash',
  'Billie',
  'Kris',
  'Hudson',
  'Lee',
  'Murphy',
  'Quincy',
  'Sasha',
  'Samar',
  'Tristan',
  'Wren',
  'Zion',
]

const lastNames = [
  'Wang',
  'Johnson',
  'Li',
  'Brown',
  'Garcia',
  'Patel',
  'Muller',
  'Nguyen',
  'Smith',
  'Rossi',
  'Martin',
  'Novak',
  'Cohen',
  'Traore',
  'Anderson',
  'Kim',
  'Papadopoulos',
  'Reyes',
  'Williams',
  'Uchida',
  'Price',
  'Russell',
  'Butler',
  'Rivera',
  'Xu',
  'Ahmed',
  'Ali',
  'Wright',
  'Vidal',
  'Kubo',
  'Whitaker',
  'Morin',
  'Wilson',
  'Thompson',
  'Murakami',
  'Young',
  'Campbell',
  'Stewart',
  'Bennett',
  'Barnes',
  'Nadir',
  'Winger',
  'Perry',
  'Edison',
  'Hawthorne',
  'Halpert',
  'Beasley',
  'Bluth',
  'Watanabe',
  'Saito',
  'Park',
  'Davis',
  'Hall',
  'Howard',
  "O'Connor",
  'Doyle',
  "O'Sullivan",
  'Nowak',
  'Gekas',
  'Bianchi',
  'De Luca',
  'Culhane',
]

const fonts = [
  "'Lato', sans-serif",
  "'Montserrat', sans-serif",
  "'Source Sans Pro', sans-serif",
  "'Raleway', sans-serif",
  "'Titillium Web', sans-serif",
  "'Roboto Slab', serif",
  "'Josefin Slab', serif",
  "'Noto Serif SC', serif",
]

export type Profile = {
  name: {
    first: string
    last: string
  }
  title: string
  bio: string
  email: {
    callToAction: string
    handle: string
  }
  font: string
}

const useRandomProfile = (): [Profile, () => void] => {
  const [profile, setProfile] = useState({
    name: {
      first: getRandomItem(firstNames),
      last: getRandomItem(lastNames),
    },
    title: getRandomItem(titles),
    bio: getRandomItem(bios),
    email: {
      callToAction: getRandomItem(emailCallsToAction),
      handle: getRandomItem(emailHandles),
    },
    font: getRandomItem(fonts),
  })

  const reroll = () => {
    setProfile({
      name: {
        first: getRandomItem(firstNames),
        last: getRandomItem(lastNames),
      },
      title: getRandomItem(titles),
      bio: getRandomItem(bios),
      email: {
        callToAction: getRandomItem(emailCallsToAction),
        handle: getRandomItem(emailHandles),
      },
      font: getRandomItem(fonts),
    })
  }

  return [profile, reroll]
}

export default useRandomProfile
